### ISSUE TITLE
Some questions to clarify

### ISSUE THREAD

**Issue by chasingegg** [Catoverflow/VBASE-artifacts#3]
Hey guys, good work!
I came here from your OSDI paper, but I have some questions to ask and look forward to your reply.
- In paper you say you implement NRA algorithm in Milvus for `multi-column query`, seems not found in the code?
- For the Relaxed Monotonicity Check, it is like an early termination method, but I don't see the experiment results that only this optimization brings.
- In the `topk with scalar filtering query`, your approach is basicly `first-vector-then-scalar-filter` manner, how about first scalar filtering then do the vector search when **scalar selectivity is low**, it will be more efficient like ADBV did. I wonder if it is due to the limitation of Volcano Model since we have to fully finish the scalar filter then vector search, cannot have an iterative search manner like `filter-vector-then-scalar-filter` did. And I think it is worth a try to compare with ADBV since it has some selectivity estimation and planning rules, but PASE doesn't have any.

**Comment by Catoverflow** [comment]
Sorry for the late reply
1. https://github.com/Catoverflow/VBASE-artifacts/tree/main/VBench/Milvus/milvus-sdk-cpp/examples/simple

2. Relaxed Monotonicity is a intrinsic property of the vector index. Our task is to stop the index search at the most appropriate moment, so we can find the optimal k. This early termination is evident when a filter is applied to exclude data, as demonstrated in both Table-5 and Table-6.

3. Our approach is not limited to "first-vector-then-scalar-filter." The database will choose different plans based on cost, and it may also opt for "first-scalar-filter-then-vector." It can do a scalar filter first, then do a KNN in brute force.
