### ISSUE TITLE
Dataset issue

### ISSUE THREAD

**Issue by whenever5225** [Catoverflow/VBASE-artifacts#4]
Hi,

I encountered an issue while downloading the dataset. The error log states: "Failed to perform copy command due to error: Login Credentials missing. No SAS token or OAuth token is present, and the resource is not public." Could you please provide guidance on how to resolve this problem? Look forward to your reply. Thank you!

Best regards,
Mengzhao Wang

**Comment by wtcl** [comment]
Hello,

I had the same problem. Could you please make the data public? 
If it is possible, it will be greatly appreciated!

Best wishes,
Student Zhang

**Comment by Catoverflow** [comment]
@wtcl @whenever5225 The repo is for artifact only, you can try email authors to ask for access. As I'm not interning at Microsoft I don't have access either
